version: "3"

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: idempotent_app
    ports:
      - "5000:80"
    environment:
      ConnectionStrings__Redis: redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
